title: Zephyr
author: Zephyr
email: 1026620934@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
  æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸»é¡µ~
  æ­£ç»äººè°å†™æ—¥è®°å•Š
  <br/>å‘å¾®å­¦ç”Ÿï¼Œåœ¨çº¿æ‰è™«ğŸ
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag
theme: jekyll-dash
# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%Y-%m-%d"

  # (optional) discqus comment configuration
  #disqus:
  #  shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/HySand
      icon: github-alt
      color: purple

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: bitbrain
  #avatar_source: local
  #avatar_path: /assets/avatar.png

# Build settings

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging